[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "7d12a210e1cc3695e72f4db818fffab06b7785fc"
os = "macos"

    [[HelloWorldC.download]]
    sha256 = "7f56aee423113c4bbf7fc8e3d93691dbf09efdf27e42fa32d2c2f43166f2e787"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.aarch64-apple-darwin.tar.xz"
[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "a2368a2caae8074bdda6e71d51acb43553fcd076"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "a08221a56b410f5558f644ee5d1a3aa8d0689afdbbaf098da06a2688a3c355bc"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.aarch64-linux-gnu.tar.xz"
[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "c790fa2a73f334c81480df0c8a57904c7da38f10"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "65f113552b2e2f66722eb0d60ff7b065ecaf4755e1a9df4f626d2c2f247cf838"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.aarch64-linux-musl.tar.xz"
[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "367eadec1a3a90f97cb67e7928c30c0859601743"
os = "freebsd"

    [[HelloWorldC.download]]
    sha256 = "5e7297c161f1c9dff6973aca9c1d0e17cbaaf47cf31f3d30b3ed21119baa3585"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.aarch64-unknown-freebsd.tar.xz"
[[HelloWorldC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bfa1637c2ecb615f0cb685a28508d772ec2ca69b"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "0e48b421e9036adac6be352f9d78e2e1dae12c15567451b94e6881833beddc1b"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.armv6l-linux-gnueabihf.tar.xz"
[[HelloWorldC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "484577a525bd00f42046d69df67699fe60d8f32b"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "fdcad75c0b4affac5022acb271a34e44b1bd6f64828aa86e8958a4bef680c9b6"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.armv6l-linux-musleabihf.tar.xz"
[[HelloWorldC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "223a135c1ba9a722640e13258cb78e5d5eb83ff6"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "e91743059fd44e209063f5e83ece70741fdf4ac4abd04c13d5094d823c4b0335"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.armv7l-linux-gnueabihf.tar.xz"
[[HelloWorldC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e67f64958ede5a4dc213cb6fc3eac5c8269f53d2"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "4a2df4763d6533706c826ada08f6c26d7678afa861328b1da3d5775b595bbc4e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.armv7l-linux-musleabihf.tar.xz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "f6cb5a80c1e825f1012ed8517d2347e0e6d10642"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "9a66021c0e72111866223d318ad9dc411b8b6183d7d8d42a3c402dd8c4c2ffae"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.i686-linux-gnu.tar.xz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "3f78df9e5994eac20094f26153c1239f4a0b57b2"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "195b8620ea247f59897441cf32e537dae0aedfc864596b08c30c8d7e82c2a233"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.i686-linux-musl.tar.xz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "cc9cfa3272d4d3844d6fcf8b6b971bd68dbc792f"
os = "windows"

    [[HelloWorldC.download]]
    sha256 = "3fb47bb70a26e5f1c04ed3ddc2d97ceab8ec79e1b5791ed22d690371c2dff757"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.i686-w64-mingw32.tar.xz"
[[HelloWorldC]]
arch = "powerpc64le"
git-tree-sha1 = "e6f5341be42da9088bbeeb566f17fc02e869b409"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "908076f65c5b09fcace43b1f46fb7a668b98fe39d93f0fa21325e9f6b92a8c3b"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.powerpc64le-linux-gnu.tar.xz"
[[HelloWorldC]]
arch = "riscv64"
git-tree-sha1 = "74baf45f365583567f29b15bfc75a3b6b0c90c2a"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "9636c24135da8dc29fa0fc2761fe1cdaef5a532ca2ef8cb11562edaebf508112"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.riscv64-linux-gnu.tar.xz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "27049ec3dfd59862d0c3a50a35565a1dfbfb5dac"
os = "macos"

    [[HelloWorldC.download]]
    sha256 = "89be2c557dab3a096f5094008ab8bcecb5a263797c441d0f794d4eaa9a33f580"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.x86_64-apple-darwin.tar.xz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "c8aa41cab66118db2387696eba33856344935ce3"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "866db1134e54dbe30eea9ed0897320b5ef6c1684c659d013bfde7ded9759d48e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.x86_64-linux-gnu.tar.xz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "38c784316c38564ebad600cec2bd5c9eb11eaa43"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "2a468ef7e2e148333b31ef46bab4128781351f93bd914a6cdea9da8f3418850c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.x86_64-linux-musl.tar.xz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "2c92d826db05624b8489c5ae7ee419e61a02d981"
os = "freebsd"

    [[HelloWorldC.download]]
    sha256 = "c2c2bfb14cc0b79cfaf600db7190ac8422ce486d6f3d9a77c070843a9fff8e2a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.x86_64-unknown-freebsd.tar.xz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "6e1eb164b0651aa44621eac4dfa340d6e60295ef"
os = "windows"

    [[HelloWorldC.download]]
    sha256 = "506fe64912be9067691cba4b1bd9aecd75ef3ed437e417b37477c9c4ad4fc691"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.2+0/HelloWorldC.v1.4.2.x86_64-w64-mingw32.tar.xz"
