# Autogenerated wrapper script for HelloWorldC_jll for x86_64-w64-mingw32
export hello_world, hello_world_doppelganger

JLLWrappers.@generate_wrapper_header("HelloWorldC")
JLLWrappers.@declare_executable_product(hello_world)
JLLWrappers.@declare_executable_product(hello_world_doppelganger)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        hello_world,
        "bin\\hello_world.exe",
    )

    JLLWrappers.@init_executable_product(
        hello_world_doppelganger,
        "bin\\hello_world.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
